### ISSUE TITLE
Return type of the `CreateMethod` is not correct

### ISSUE THREAD

**Issue by kostysh** [pulsecron/pulse#20]
Here is the type of the `CreateMethod`:

```typescript
export type CreateMethod = <T extends JobAttributesData>(name: string, data: T) => Job; // `Job` is not properly typed
```

`Job` itself has the following type:

```typescript
declare class Job<T extends JobAttributesData = JobAttributesData> { /* ... */ }
```

This way a return type of the `CreateMethod` has to look like this:

```typescript
export type CreateMethod = <T extends JobAttributesData>(name: string, data: T) => Job<T>;
```

**Comment by kostysh** [comment]
@code-xhyun maybe it will be more helpful if I will create PRs from time to time? Not too often )

**Comment by code-xhyun** [comment]
@kostysh Sure! We welcome your participation!

**Comment by kostysh** [comment]
https://github.com/pulsecron/pulse/pull/21
