### ISSUE TITLE
Can't schedule multiple similar tasks

### ISSUE THREAD

**Issue by dev-folks** [pulsecron/pulse#52]
### Description

I'm trying to schedule multiple recurring jobs that are similar but have different fields in `job.attrs.data`.

```
await this.pulse.every(
  task.cronExp,
  EVENT_JOBS[task.assetType.toUpperCase()].START,
  { taskId: id },
);
```

Behavior: All active jobs with the same name disappear.

I found the reason in the library code. A new job with the type "single" overwrites the existing one. However, the comments mention that the purpose of the 'single' job type is unknown.

Do you have any idea why this might be done?

<img width="1088" alt="Screenshot 2024-08-20 at 17 02 38" src="https://github.com/user-attachments/assets/0695eb82-641e-44aa-a077-7e7ebba332b9">

**Comment by dev-folks** [comment]
For now, I’ve added a workaround for this in my code.

```
const jobs = await this.pulse.every(
  task.cronExp,
  EVENT_JOBS[task.assetType.toUpperCase()].START,
  { taskId: id },
);

await Promise.all(
  [].concat(jobs).map((job) => {
    job.attrs.type = 'normal';
    return job.save();
  }),
);
```

**Comment by code-xhyun** [comment]
By default, when creating a job with the same name using pulse.every, the new job overwrites the existing one, ensuring a 'single' instance.
If you want to create multiple jobs with the same name, it's recommended to use pulse.create as shown in the code below

```
  const job = pulse.create('delete old users', { data: { taskId: randomId } });

  await job.repeatEvery('*/1 * * * *').save();
  
```

**Comment by dev-folks** [comment]
Oh, my inattention... Thanks a lot!
